name: "FlyWheel Development Website"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v5.0.2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ssh.getflywheel.com
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        ARGS: -rltgoDzvO --exclude .git --exclude .github
        TARGET: /www/wp-content/themes/